language: node_js
node_js: node

install:
- npm ci

cache: npm

branches:
  only:
  - master

script:
  - echo "No build step neccesary..."

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npm run semantic-release